theme = "catppuccin_latte"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
true-color = true
idle-timeout = 0

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = [
    "diagnostics",
    "selections",
    "position-percentage",
    "position",
    "file-encoding",
    "file-line-ending",
    "file-type"
]
