[[language]]
name = "cpp"
scope = "source.cpp"
injection-regex = "cpp"
file-types = ["cc", "cpp", "hpp", "h", "tpp"]
language-servers = [ "clangd" ]
indent = { tab-width = 4, unit = "    " }

[language-server.clangd.config]
command = "clangd"
args = ["-std=c++23", "-Wall"]
config = { "fallbackFlags" = ["-std=c++23", "-Wall"] }

[[language]]
name = "python"
language-servers = [ "pylsp" ]
indent = { tab-width = 4, unit = "    " }

[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
language-servers = ["rust-analyzer"]
indent = { tab-width = 4, unit = "    " }

[language-server.rust-analyzer.config]
cargo.features = "all"
rust-analyzer.check.command = "clippy"
